# Generated by Django 4.1.1 on 2022-10-01 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetrolStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', models.CharField(max_length=20, verbose_name='Координаты')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'АЗС',
                'verbose_name_plural': 'Список АЗС',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название топлива')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена топлива')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('petrol_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='store.petrolstore', verbose_name='АЗС')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Список цен',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='logos')),
                ('petrol_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.petrolstore', verbose_name='АЗС')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Список изображений',
            },
        ),
    ]
