# Generated by Django 4.1.1 on 2022-10-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='price',
            name='petrol_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='store.petrolstore', verbose_name='АЗС'),
        ),
        migrations.AlterField(
            model_name='service',
            name='petrols',
            field=models.ManyToManyField(blank=True, related_name='services', to='store.petrolstore', verbose_name='АЗС'),
        ),
    ]
